### ISSUE TITLE
How tio use the Draw Bitmap block

### ISSUE THREAD

**Issue by dsssssssss9** [Shorts1999/ptx-smartmatrix#5]
Hi

I can't work out how to use the Draw Bitmap block - any chance you could add a quick example to the README.md file please?

For example how would i go about displaying  a 3x3 square ?
I setup the array with the values 1,1,1,1,0,1,1,1,1 & set height & width as 3  but i do not get a square. Best i can get is by setting width to 1 / height to 9 in which case a get a 9 pixel vertical line with the center pixel turned off

Also the  x coordinate seems to be to set so that a value of 0 is the top centre of the panel , with top left / right being -7 / 7 respectively

regards

**Comment by Shorts1999** [comment]
Hello,

I used to work on this project at my old job, since I no longer work there I no longer have a Micro:Bit or display to test the library with. The library has also only been tested with one size of display so other dimensions might still have bugs. I'm very sorry but it's been a long time since I worked on this and do not plan to release any upates  to it in the near future.

I hope you can find a way to solve the issues yourself or maybe another library is available with better support. my apologies.

Regards

**Comment by dsssssssss9** [comment]
Hi
No apologies needed

Apart from this it is a great Library & will be very useful!!

Thanks for taking the time to get back to me

Regards
