### ISSUE TITLE
Any Chance of making this work with Progressive type displays

### ISSUE THREAD

**Issue by dsssssssss9** [Shorts1999/ptx-smartmatrix#6]

**Comment by dsssssssss9** [comment]
sorry opened this by mistake

**Comment by Shorts1999** [comment]
Hi, I see you've deleted the description now but I saw you were asking for different display type compatibility (mainly progressive isntead of zigzag)
I have not worked on this library in a couple years but I could be interested in opening it up again since I got some time on my hands.
I'll have to get a microbit and some displays again since I originally made this while working at a company that supplied them for me where I no longer work so it might take a couple weeks but it is definitely possible to make it compatible. I'll look into it

**Comment by dsssssssss9** [comment]
Hi
so sorry to have bothered you 
realised after posting the issue that we had already been in contact previously .

I am trying to help a friend in USA who teaches STEM - involves lots of projects involving Micro:Bit & Makecode,

I have a request from him to try to find a way of easily display text on matrix display in MakeCode. Your extension is by far the closest i have found! 

As we cannot guarantee which style of matrix they have plus many of his projects use a matrix called ColorBit from china that are progressive style.

If i can help with a few units of your local currency for a Micro:Bit or a matrix please let me know!!

Can i also add a request for a way to display static text as well?

Regards & Thanks

Jason

**Comment by Shorts1999** [comment]
Hello Jason,

It's very kind of you to offer, but my restrictions are more in my time than in money. I've ordered some new LED-strips to make some matrix panels to try and work on it!
I should be able to get some work done over the weekend and I will keep you updated.
As for the text goes, that should definitely be possible too! I'll look into it
